-- Switch to the database created by docker environment variables
USE testdb;

-- Create the employees table
CREATE TABLE IF NOT EXISTS employees (
    emp_id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    department VARCHAR(50) NOT NULL,
    status VARCHAR(20) DEFAULT 'Active',
    hire_date DATE NOT NULL
);

-- Insert 100 sample employees
INSERT INTO employees (first_name, last_name, email, department, hire_date) VALUES
('James', 'Smith', 'james.smith@example.com', 'Engineering', '2020-01-15'),
('Mary', 'Johnson', 'mary.johnson@example.com', 'Marketing', '2020-02-10'),
('John', 'Williams', 'john.williams@example.com', 'Sales', '2020-03-05'),
('Patricia', 'Brown', 'patricia.brown@example.com', 'Finance', '2020-04-20'),
('Robert', 'Jones', 'robert.jones@example.com', 'Engineering', '2020-05-12'),
('Jennifer', 'Garcia', 'jennifer.garcia@example.com', 'Human Resources', '2020-06-18'),
('Michael', 'Miller', 'michael.miller@example.com', 'IT', '2020-07-22'),
('Linda', 'Davis', 'linda.davis@example.com', 'Marketing', '2020-08-30'),
('William', 'Rodriguez', 'william.rodriguez@example.com', 'Sales', '2020-09-15'),
('Elizabeth', 'Martinez', 'elizabeth.martinez@example.com', 'Finance', '2020-10-05'),
('David', 'Hernandez', 'david.hernandez@example.com', 'Engineering', '2020-11-12'),
('Barbara', 'Lopez', 'barbara.lopez@example.com', 'Human Resources', '2020-12-01'),
('Richard', 'Gonzalez', 'richard.gonzalez@example.com', 'IT', '2021-01-10'),
('Susan', 'Wilson', 'susan.wilson@example.com', 'Marketing', '2021-02-14'),
('Joseph', 'Anderson', 'joseph.anderson@example.com', 'Sales', '2021-03-22'),
('Jessica', 'Thomas', 'jessica.thomas@example.com', 'Finance', '2021-04-18'),
('Thomas', 'Taylor', 'thomas.taylor@example.com', 'Engineering', '2021-05-30'),
('Sarah', 'Moore', 'sarah.moore@example.com', 'Human Resources', '2021-06-15'),
('Charles', 'Jackson', 'charles.jackson@example.com', 'IT', '2021-07-25'),
('Karen', 'Martin', 'karen.martin@example.com', 'Marketing', '2021-08-10'),
('Christopher', 'Lee', 'christopher.lee@example.com', 'Sales', '2021-09-05'),
('Nancy', 'Perez', 'nancy.perez@example.com', 'Finance', '2021-10-20'),
('Daniel', 'Thompson', 'daniel.thompson@example.com', 'Engineering', '2021-11-15'),
('Lisa', 'White', 'lisa.white@example.com', 'Human Resources', '2021-12-10'),
('Matthew', 'Harris', 'matthew.harris@example.com', 'IT', '2022-01-05'),
('Betty', 'Sanchez', 'betty.sanchez@example.com', 'Marketing', '2022-02-28'),
('Anthony', 'Clark', 'anthony.clark@example.com', 'Sales', '2022-03-15'),
('Margaret', 'Ramirez', 'margaret.ramirez@example.com', 'Finance', '2022-04-10'),
('Mark', 'Lewis', 'mark.lewis@example.com', 'Engineering', '2022-05-22'),
('Sandra', 'Robinson', 'sandra.robinson@example.com', 'Human Resources', '2022-06-18'),
('Donald', 'Walker', 'donald.walker@example.com', 'IT', '2022-07-30'),
('Ashley', 'Young', 'ashley.young@example.com', 'Marketing', '2022-08-12'),
('Steven', 'Allen', 'steven.allen@example.com', 'Sales', '2022-09-25'),
('Kimberly', 'King', 'kimberly.king@example.com', 'Finance', '2022-10-15'),
('Paul', 'Wright', 'paul.wright@example.com', 'Engineering', '2022-11-05'),
('Emily', 'Scott', 'emily.scott@example.com', 'Human Resources', '2022-12-20'),
('Andrew', 'Torres', 'andrew.torres@example.com', 'IT', '2023-01-10'),
('Donna', 'Nguyen', 'donna.nguyen@example.com', 'Marketing', '2023-02-15'),
('Joshua', 'Hill', 'joshua.hill@example.com', 'Sales', '2023-03-05'),
('Michelle', 'Flores', 'michelle.flores@example.com', 'Finance', '2023-04-22'),
('Kenneth', 'Green', 'kenneth.green@example.com', 'Engineering', '2023-05-18'),
('Carol', 'Adams', 'carol.adams@example.com', 'Human Resources', '2023-06-12'),
('Kevin', 'Nelson', 'kevin.nelson@example.com', 'IT', '2023-07-25'),
('Amanda', 'Baker', 'amanda.baker@example.com', 'Marketing', '2023-08-30'),
('Brian', 'Hall', 'brian.hall@example.com', 'Sales', '2023-09-10'),
('Melissa', 'Rivera', 'melissa.rivera@example.com', 'Finance', '2023-10-15'),
('George', 'Campbell', 'george.campbell@example.com', 'Engineering', '2023-11-05'),
('Deborah', 'Mitchell', 'deborah.mitchell@example.com', 'Human Resources', '2023-12-20'),
('Edward', 'Carter', 'edward.carter@example.com', 'IT', '2024-01-12'),
('Stephanie', 'Roberts', 'stephanie.roberts@example.com', 'Marketing', '2024-02-18'),
('Ronald', 'Gomez', 'ronald.gomez@example.com', 'Sales', '2024-03-25'),
('Rebecca', 'Phillips', 'rebecca.phillips@example.com', 'Finance', '2024-04-10'),
('Timothy', 'Evans', 'timothy.evans@example.com', 'Engineering', '2024-05-30'),
('Sharon', 'Turner', 'sharon.turner@example.com', 'Human Resources', '2024-06-15'),
('Jason', 'Diaz', 'jason.diaz@example.com', 'IT', '2024-07-05'),
('Laura', 'Parker', 'laura.parker@example.com', 'Marketing', '2024-08-22'),
('Jeffrey', 'Cruz', 'jeffrey.cruz@example.com', 'Sales', '2024-09-12'),
('Cynthia', 'Edwards', 'cynthia.edwards@example.com', 'Finance', '2024-10-18'),
('Ryan', 'Collins', 'ryan.collins@example.com', 'Engineering', '2024-11-25'),
('Kathleen', 'Reyes', 'kathleen.reyes@example.com', 'Human Resources', '2024-12-10'),
('Jacob', 'Stewart', 'jacob.stewart@example.com', 'IT', '2025-01-05'),
('Amy', 'Morris', 'amy.morris@example.com', 'Marketing', '2025-02-28'),
('Gary', 'Morales', 'gary.morales@example.com', 'Sales', '2025-03-15'),
('Shirley', 'Murphy', 'shirley.murphy@example.com', 'Finance', '2025-04-20'),
('Nicholas', 'Cook', 'nicholas.cook@example.com', 'Engineering', '2025-05-12'),
('Angela', 'Rogers', 'angela.rogers@example.com', 'Human Resources', '2025-06-18'),
('Eric', 'Gutierrez', 'eric.gutierrez@example.com', 'IT', '2025-07-30'),
('Helen', 'Ortiz', 'helen.ortiz@example.com', 'Marketing', '2025-08-10'),
('Jonathan', 'Morgan', 'jonathan.morgan@example.com', 'Sales', '2025-09-05'),
('Anna', 'Cooper', 'anna.cooper@example.com', 'Finance', '2025-10-22'),
('Stephen', 'Peterson', 'stephen.peterson@example.com', 'Engineering', '2025-11-15'),
('Brenda', 'Bailey', 'brenda.bailey@example.com', 'Human Resources', '2025-12-05'),
('Larry', 'Reed', 'larry.reed@example.com', 'IT', '2026-01-20'),
('Pamela', 'Kelly', 'pamela.kelly@example.com', 'Marketing', '2026-02-12'),
('Justin', 'Howard', 'justin.howard@example.com', 'Sales', '2026-03-18'),
('Nicole', 'Ramos', 'nicole.ramos@example.com', 'Finance', '2026-04-25'),
('Scott', 'Kim', 'scott.kim@example.com', 'Engineering', '2026-05-10'),
('Emma', 'Cox', 'emma.cox@example.com', 'Human Resources', '2026-06-15'),
('Brandon', 'Ward', 'brandon.ward@example.com', 'IT', '2026-07-05'),
('Samantha', 'Richardson', 'samantha.richardson@example.com', 'Marketing', '2026-08-22'),
('Benjamin', 'Watson', 'benjamin.watson@example.com', 'Sales', '2026-09-12'),
('Katherine', 'Brooks', 'katherine.brooks@example.com', 'Finance', '2026-10-18'),
('Samuel', 'Chavez', 'samuel.chavez@example.com', 'Engineering', '2026-11-30'),
('Christine', 'Wood', 'christine.wood@example.com', 'Human Resources', '2026-12-15'),
('Gregory', 'James', 'gregory.james@example.com', 'IT', '2027-01-10'),
('Debra', 'Bennett', 'debra.bennett@example.com', 'Marketing', '2027-02-28'),
('Frank', 'Gray', 'frank.gray@example.com', 'Sales', '2027-03-05'),
('Rachel', 'Mendoza', 'rachel.mendoza@example.com', 'Finance', '2027-04-20'),
('Raymond', 'Ruiz', 'raymond.ruiz@example.com', 'Engineering', '2027-05-15'),
('Carolyn', 'Hughes', 'carolyn.hughes@example.com', 'Human Resources', '2027-06-10'),
('Patrick', 'Price', 'patrick.price@example.com', 'IT', '2027-07-25'),
('Janet', 'Alvarez', 'janet.alvarez@example.com', 'Marketing', '2027-08-30'),
('Alexander', 'Castillo', 'alexander.castillo@example.com', 'Sales', '2027-09-15'),
('Catherine', 'Sanders', 'catherine.sanders@example.com', 'Finance', '2027-10-05'),
('Jack', 'Patel', 'jack.patel@example.com', 'Engineering', '2027-11-12'),
('Maria', 'Myers', 'maria.myers@example.com', 'Human Resources', '2027-12-01'),
('Dennis', 'Long', 'dennis.long@example.com', 'IT', '2028-01-18'),
('Heather', 'Ross', 'heather.ross@example.com', 'Marketing', '2028-02-14'),
('Jerry', 'Foster', 'jerry.foster@example.com', 'Sales', '2028-03-22'),
('Diane', 'Jimenez', 'diane.jimenez@example.com', 'Finance', '2028-04-10');