services:

  ingress:
    image: nginx:1.31.0-alpine-slim
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
    networks:
      - myapp
    configs:
      - source: ingress_config
        target: /etc/nginx/conf.d/default.conf
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.25'
          memory: 128M
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  mysql:
    image: wachira90/mysql:5.7.36
    volumes:
      - db_data:/var/lib/mysql:rw
    environment:
      MYSQL_USER: sysadmin
      MYSQL_DATABASE: testdb
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    configs:
      - source: my_init_script
        target: /docker-entrypoint-initdb.d/initdb.sql
    command: --query_cache_type=1 --query-cache-limit=524288 --query-cache-min-res-unit=2048 --query-cache-size=83886080 --explicit_defaults_for_timestamp
    ports:
      - "3306:3306"
    networks:
      - myapp
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
      restart_policy:
        condition: any
    secrets:
      - db_password
      - db_root_password

  adminer:
    image: wachira90/adminer:4.7.8
    ports:
      - "8000:8080"
    networks:
      - myapp
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
      restart_policy:
        condition: any

  web:
      image: php:8.3.31-fpm
      ports:
        - "7000:8080"
      networks:
        - myapp
      configs:
        - source: web_file
          target: /var/www/html/index.php
      command: ["php", "-S", "0.0.0.0:8080", "-d", "display_errors=1", "-t", "/var/www/html/"]

  api:
      image: docker.io/library/myphp:v1
      # image: php:8.3.31-fpm
      ports:
        - "7001:8080"
      networks:
        - myapp
      configs:
        - source: api_file
          target: /var/www/html/index.php
      command: ["php", "-S", "0.0.0.0:8080", "-d", "display_errors=1", "-t", "/var/www/html/"]

configs:
  ingress_config:
    file: ./default.conf
  my_init_script:
    file: ./initdb.sql
  web_file:
    file: ./index.php
  api_file:
    # file: ./api.php
    file: ./apidb.php

volumes:
  db_data:

networks:
  myapp:
    driver: overlay

secrets:
  db_password:
    file: ./mysql_password.txt
  db_root_password:
    file: ./mysql_root_password.txt

# docker stack deploy -c test.yml app --detach=false
# docker stack ps app
# docker stack services app
# WEB-URL: http://app.127-0-0-1.nip.io
# API-URL: http://app.127-0-0-1.nip.io/api
# DB-URL: http://db.127-0-0-1.nip.io

# docker service update --image nginx:1.30.2-alpine-slim app_www
# docker service update --image nginx:1.31.0-alpine-slim app_www

# docker stack rm app